language: ruby

rvm:
  - 2.5
  - 2.6

cache:
  directories:
  - $HOME/nats-server

before_install:
  - bash ./scripts/install_gnatsd.sh

before_script:
  - export PATH=$HOME/nats-server:$PATH

sudo: required
dist: xenial
bundler_args: --without server

addons:
  hosts:
    - server-A.clients.nats-service.localhost
    - server-A.clients.fake-nats-service.localhost
    - server-A.routes.nats-service.localhost
    - server-A.routes.fake-nats-service.localhost
