sudo: false

rvm:
  # - 2.2
  - 2.3.0
  # - 2.4.0-preview1
  # - ruby-head  

cache:
  directories:
  - $HOME/gnatsd

before_install:
  - bash ./scripts/install_gnatsd.sh

before_script:
  - export PATH=$HOME/gnatsd:$PATH

sudo: required
dist: trusty
bundler_args: --without server

matrix:
  include:

    # - rvm: jruby
    #   env: JRUBY_OPTS='--server -Xcompile.invokedynamic=false'
    #   script: "bundle exec rake spec:client:jruby"
    #   jdk: openjdk7

    # - rvm: jruby
    #   env: JRUBY_OPTS='--server -Xcompile.invokedynamic=false'
    #   script: "bundle exec rake spec:client:jruby"
    #   jdk: oraclejdk7

    # - rvm: jruby
    #   env: JRUBY_OPTS='--server -Xcompile.invokedynamic=false'
    #   script: "bundle exec rake spec:client:jruby"
    #   jdk: openjdk8

    # - rvm: jruby
    #   env: JRUBY_OPTS='--server -Xcompile.invokedynamic=false'
    #   script: "bundle exec rake spec:client:jruby"
    #   jdk: oraclejdk8

    # - rvm: jruby
    #   env: JRUBY_OPTS='--server -Xcompile.invokedynamic=false'  JAVA_OPTS='-Djava.security.egd=file:///dev/urandom'
    #   script: "bundle exec rake spec:client:jruby:inboxes"
    #   jdk: openjdk7

    # - rvm: jruby
    #   env: JRUBY_OPTS='--server -Xcompile.invokedynamic=false'  JAVA_OPTS='-Djava.security.egd=file:///dev/urandom'
    #   script: "bundle exec rake spec:client:jruby:inboxes"
    #   jdk: oraclejdk7

    - rvm: jruby
      env: JRUBY_OPTS='--server -Xcompile.invokedynamic=false ' JAVA_OPTS='-Djava.security.egd=file:///dev/urandom'
      script: "bundle exec rake spec:client:jruby:inboxes"
      jdk: openjdk8

    - rvm: jruby
      env: JRUBY_OPTS='--server -Xcompile.invokedynamic=false'  JAVA_OPTS='-Djava.security.egd=file:///dev/urandom'
      script: "bundle exec rake spec:client:jruby:inboxes"
      jdk: oraclejdk8

    - rvm: jruby-head
      env: JRUBY_OPTS='--server -Xcompile.invokedynamic=false'  JAVA_OPTS='-Djava.security.egd=file:///dev/urandom'
      script: "bundle exec rake spec:client:jruby:inboxes"
      jdk: oraclejdk8
      
  allow_failures:

    # - rvm: jruby
    #   env: JRUBY_OPTS='--server -Xcompile.invokedynamic=false'
    #   jdk: openjdk7

    # - rvm: jruby
    #   env: JRUBY_OPTS='--server -Xcompile.invokedynamic=false'
    #   jdk: oraclejdk7

    - rvm: jruby
      env: JRUBY_OPTS='--server -Xcompile.invokedynamic=false'
      jdk: openjdk8

    - rvm: jruby
      env: JRUBY_OPTS='--server -Xcompile.invokedynamic=false'
      jdk: oraclejdk8

    - rvm: jruby-head
      env: JRUBY_OPTS='--server -Xcompile.invokedynamic=false'
      jdk: oraclejdk8

    # - rvm: ruby-head

    # - rvm: 2.4.0-preview1
